<?php
declare(strict_types=1);

// Techvpn SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

TechvpnUtility::setRegistrar(function (TechvpnUtility $u): void {
    $u->clean = [TechvpnClean::class, 'call'];
    $u->done = [TechvpnDone::class, 'call'];
    $u->make_error = [TechvpnMakeError::class, 'call'];
    $u->feature_add = [TechvpnFeatureAdd::class, 'call'];
    $u->feature_hook = [TechvpnFeatureHook::class, 'call'];
    $u->feature_init = [TechvpnFeatureInit::class, 'call'];
    $u->fetcher = [TechvpnFetcher::class, 'call'];
    $u->make_fetch_def = [TechvpnMakeFetchDef::class, 'call'];
    $u->make_context = [TechvpnMakeContext::class, 'call'];
    $u->make_options = [TechvpnMakeOptions::class, 'call'];
    $u->make_request = [TechvpnMakeRequest::class, 'call'];
    $u->make_response = [TechvpnMakeResponse::class, 'call'];
    $u->make_result = [TechvpnMakeResult::class, 'call'];
    $u->make_point = [TechvpnMakePoint::class, 'call'];
    $u->make_spec = [TechvpnMakeSpec::class, 'call'];
    $u->make_url = [TechvpnMakeUrl::class, 'call'];
    $u->param = [TechvpnParam::class, 'call'];
    $u->prepare_auth = [TechvpnPrepareAuth::class, 'call'];
    $u->prepare_body = [TechvpnPrepareBody::class, 'call'];
    $u->prepare_headers = [TechvpnPrepareHeaders::class, 'call'];
    $u->prepare_method = [TechvpnPrepareMethod::class, 'call'];
    $u->prepare_params = [TechvpnPrepareParams::class, 'call'];
    $u->prepare_path = [TechvpnPreparePath::class, 'call'];
    $u->prepare_query = [TechvpnPrepareQuery::class, 'call'];
    $u->graphql_body = [TechvpnGraphql::class, 'body'];
    $u->graphql_errors = [TechvpnGraphql::class, 'errors'];
    $u->result_basic = [TechvpnResultBasic::class, 'call'];
    $u->result_body = [TechvpnResultBody::class, 'call'];
    $u->result_headers = [TechvpnResultHeaders::class, 'call'];
    $u->transform_request = [TechvpnTransformRequest::class, 'call'];
    $u->transform_response = [TechvpnTransformResponse::class, 'call'];
});
